### ISSUE TITLE
Panic when guild.Members

### ISSUE THREAD

**Issue by juby210-PL** [andersfylling/disgord#152]
**Describe the bug**
When I try to get a member comes out panic runtime error

**Error messages**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x148 pc=0x7af536]

goroutine 56 [running]:
github.com/andersfylling/disgord.(*Guild).Member(0x0, 0x4814a6ef9c40003, 0x0, 0x0, 0x0)
        /home/juby/go/pkg/mod/github.com/andersfylling/disgord@v0.11.1/guild.go:478 +0x26
```

**Desktop (please complete the following information):**
 - Golang version: go1.12 linux/amd64
 - Using Go modules? yes

**Additional context**
My code:
```go
				msg := data.Message
				g, _ := s.GetGuild(msg.GuildID)
				m, _ := g.Member(msg.Author.ID)
```

**Comment by andersfylling** [comment]
Hi, which version of disgord are you using?

**Comment by andersfylling** [comment]
Can you expand your code so I can see the entire function?

**Comment by juby210-PL** [comment]
```go
func handler(s disgord.Session, data *disgord.MessageCreate) {
	msg := data.Message
	args := strings.Split(msg.Content, " ")

	if args[0] == "give" {
		if len(args) == 1 {
			msg.Reply(s, "Give role color hex (#xxxxxx)")
		} else {
			validColor := regexp.MustCompile(`^#?([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$`)
			if validColor.MatchString(args[1]) {
				color := strings.ToLower(args[1])
				if !strings.HasPrefix(color, "#") {
					color = "#" + color
				}

				g, _ := s.GetGuild(msg.GuildID)
				m, _ := g.Member(msg.Author.ID)
				var cr *disgord.Role

				for i := 0; i < len(m.Roles); i++ {
					r, _ := g.Role(m.Roles[i])
					if strings.HasPrefix(r.Name, "color: ") {
						cr = r
					}
				}
				if cr != nil && cr.Name == "color: "+color {
					s.AddGuildMemberRole(g.ID, msg.Author.ID, cr.ID)
					msg.Reply(s, "Color added "+color)
				} else {
					var role *disgord.Role
					for i := 0; i < len(g.Roles); i++ {
						if g.Roles[i].Name == "color: "+color {
							role = g.Roles[i]
						}
					}
					msg.Reply(s, "Color added "+color)
					s.AddGuildMemberRole(g.ID, msg.Author.ID, role.ID)
					if roleMembersCount(g, cr.ID) <= 1 {
						g.DeleteRoleByID(cr.ID)
					} else {
						s.RemoveGuildMemberRole(g.ID, msg.Author.ID, cr.ID)
					}
				}
			} else {
				msg.Reply(s, "The color must be in the hex format")
			}
		}
	}
}```

**Comment by andersfylling** [comment]
can you add error handling and let me know what the error is?
```go
g, err := s.GetGuild(msg.GuildID)
if err != nil {
	panic(err)
}
m, err := g.Member(msg.Author.ID)
if err != nil {
	panic(err)
}
```

**Comment by juby210-PL** [comment]
```
panic: Missing Access

goroutine 44 [running]:
main.handler(0x9c1ce0, 0xc0000e22c0, 0xc00038c300)
        /media/juby/220GB/go/ColorRoles/main.go:35 +0xb20
github.com/andersfylling/disgord.(*dispatcher).trigger(0xc0000c0280, 0x86dec0, 0x930370, 0x8b88e0, 0xc00038c300)
        /home/juby/go/pkg/mod/github.com/andersfylling/disgord@v0.11.1/reactor_gen.go:194 +0x199
github.com/andersfylling/disgord.(*dispatcher).dispatch(0xc0000c0280, 0x9b3d20, 0xc0000b6078, 0xc0000b6ac0, 0xe, 0x8b88e0, 0xc0000aad80)
        /home/juby/go/pkg/mod/github.com/andersfylling/disgord@v0.11.1/reactor.go:164 +0x130
created by github.com/andersfylling/disgord.demultiplexer
        /home/juby/go/pkg/mod/github.com/andersfylling/disgord@v0.11.1/reactor.go:76 +0x274
exit status 2
```

**Comment by andersfylling** [comment]
is the msg.GuildID == 0?

**Comment by juby210-PL** [comment]
yes

**Comment by andersfylling** [comment]
I just checked in the discord api server. And I had completely forgotten that GuildId will ofc be 0 if this is not a message from a guild. 

So you can assume that if the GuildID == 0, it is a private message.

To the top of your handler func, I would add:
```go
if msg.GuildID == 0 {
	return // direct message
}
```

**Comment by juby210-PL** [comment]
Hm, but I send message on guild channel, not pm.

**Comment by andersfylling** [comment]
Oh, that's not good.

Can you build disgord with the build tag "disgord_diagnosews"?

`go build -tags="disgord_diagnosews" .`
Run the new file as you normally do and then stop it once you have sent that guild message. A folder should have been created in the same directory as you ran the bot. Look for "diagnose-report/packets" where you should see every event discord has sent as a json file. 

The one we care about here are those with the word "MESSAGE_CREATE" in them. See if you can get the right one and post the json here. 

I believe this to be a disgord issue, but its nice to verify before I start digging.

**Comment by juby210-PL** [comment]
I try to run this build but i can't see any new file. In what directory should I do build?

**Comment by juby210-PL** [comment]
```json
{
	"t": "MESSAGE_CREATE",
	"s": 4,
	"op": 0,
	"d": {
		"type": 0,
		"tts": false,
		"timestamp": "2019-07-06T11:34:36.832000+00:00",
		"pinned": false,
		"nonce": "597027619245916160",
		"mentions": [],
		"mention_roles": [],
		"mention_everyone": false,
		"member": {
			"roles": [
				"560520665959235584",
				"596776407036723211",
				"485101930360602653"
			],
			"premium_since": null,
			"nick": "xXxJubyMCPLYTxXx",
			"mute": false,
			"joined_at": "2018-08-04T14:25:28.457000+00:00",
			"deaf": false
		},
		"id": "597027619946496030",
		"embeds": [],
		"edited_timestamp": null,
		"content": "&give #00ff00",
		"channel_id": "475311129841631262",
		"author": {
			"username": "Juby210",
			"id": "324622488644616195",
			"discriminator": "2100",
			"avatar": "84aa5f5e926325cd94cb78dfd0cb8b92"
		},
		"attachments": [],
		"guild_id": "475308295184449537"
	}
}
```

**Comment by andersfylling** [comment]
Thank you, I will test this out.

**Comment by andersfylling** [comment]
This seems to be an issue with v0.11.1. Please upgrade to disgord v0.11.2 :)

**Comment by juby210-PL** [comment]
Oh ok upgrade to v0.11.2 fixed this, thanks :)
