### ISSUE TITLE
Startup error, Raspberry pi 4B

### ISSUE THREAD

**Issue by Karitham** [andersfylling/disgord#297]
**Describe the bug**
When following the steps for a startup bot on the Readme, the bot crashes at startup on my rpi.
After reproducing the steps inducing the crash on my computer, everything works well.

**Expected behavior**
The bot starts and logs the messages.

**Error messages**
```sh
pi@raspberrypi ~/Gobot> go run .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12554]

goroutine 1 [running]:
runtime/internal/atomic.goXadd64(0x10e44d4, 0x1, 0x0, 0x44191a, 0x1)
    /usr/local/go/src/runtime/internal/atomic/atomic_arm.go:103 +0x1c
go.uber.org/atomic.(*Uint64).Add(...)
    /home/pi/go/pkg/mod/go.uber.org/atomic@v1.4.0/atomic.go:190
github.com/andersfylling/disgord/internal/gateway.(*client).getLogPrefix(0x10e43c0, 0x1, 0x1)
    /home/pi/go/pkg/mod/github.com/andersfylling/disgord@v0.17.0/internal/gateway/client.go:256 +0x8c
github.com/andersfylling/disgord/internal/gateway.(*client).reconnectLoop(0x10e43c0, 0x116ca60, 0x1147d5c)
    /home/pi/go/pkg/mod/github.com/andersfylling/disgord@v0.17.0/internal/gateway/client.go:331 +0x2c
github.com/andersfylling/disgord/internal/gateway.(*shardMngr).Connect(0x1018180, 0x0, 0x0)
    /home/pi/go/pkg/mod/github.com/andersfylling/disgord@v0.17.0/internal/gateway/sharding.go:325 +0xd8
github.com/andersfylling/disgord.(*Client).Connect(0x11161e0, 0x4db928, 0x101e060, 0x0, 0x0)
    /home/pi/go/pkg/mod/github.com/andersfylling/disgord@v0.17.0/client.go:444 +0x354
github.com/andersfylling/disgord.(*Client).StayConnectedUntilInterrupted(0x11161e0, 0x4db928, 0x101e060, 0x1045fa0, 0x1)
    /home/pi/go/pkg/mod/github.com/andersfylling/disgord@v0.17.0/client.go:500 +0x44
main.main()
    /home/pi/Gobot/main.go:29 +0x140
exit status 2
```

**Desktop (please complete the following information):**
 - Golang version: go 1.14.3 linux/arm
 - Using Go modules? no, using the script in the readme
 - Disgord version? latest version

**Additional context**
Using rpi4, everything updated and working, go works as expected while doing other things.

**Comment by andersfylling** [comment]
I believe this is related: https://github.com/golang/go/issues/23345

It seems to be a issue with Go. I am not entirely certain how to fix this right now.

**Comment by Karitham** [comment]
We can see the same kind of error with this code, so the error most probably come from `sync/atomic`

```sh
pi@raspberrypi ~> mkdir testgo
pi@raspberrypi ~> cd testgo
pi@raspberrypi ~/testgo> vim main.go
pi@raspberrypi ~/testgo> cat main.go
package main

import "sync/atomic"

type X struct {
    foo int8
    bar uint64
}

func main() {
    x := X{bar: 1}
    atomic.AddUint64(&x.bar, 1)
    println("bar=", x.bar)
}
pi@raspberrypi ~/testgo> go run .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11c34]

goroutine 1 [running]:
runtime/internal/atomic.goXadd64(0x1816064, 0x1, 0x0, 0x0, 0x0)
    /usr/local/go/src/runtime/internal/atomic/atomic_arm.go:103 +0x1c
main.main()
    /home/pi/testgo/main.go:12 +0x48
exit status 2
```
