### ISSUE TITLE
UserUpdate pushes out a nil pointer for the bot users updates

### ISSUE THREAD

**Issue by JakeMakesStuff** [andersfylling/disgord#300]
**Describe the bug**
the UserUpdate event seems to push out a nil pointer for the bot user if it is changed.

**Expected behavior**
Either the event is dispatched for the bot user (personally I'd prefer this) or it is documented.

**Error messages**
N/A

**Desktop (please complete the following information):**
 - Golang version: [e.g. v1.13.1] v1.14.2
 - Using Go modules? [yes/no] yes
 - Disgord version? [e.g. v0.15] v0.17.2
 - Connected to the gateway before using REST methods? [yes/no] yes

**Additional context**
Here's an example code block which can be used to recreate it (will print a nil pointer):
```go
func main() {
    s := disgord.New(disgord.Config{
        BotToken: os.Getenv("TOKEN"),
    })
    s.On(disgord.EvtUserUpdate, func(_ disgord.Session, evt *disgord.UserUpdate) {
        println(evt.User)
    })
    err := s.StayConnectedUntilInterrupted(context.TODO())
    if err != nil {
        panic(err)
    }
}
```

**Comment by andersfylling** [comment]
Hi, please try the latest commit =)

**Comment by JakeMakesStuff** [comment]
Hi @andersfylling,

Unfortunately the latest commit didn't seem to work for me. When I try with this commit, I get this stack trace which seems to be a internal bug in disgord:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13cf473]

goroutine 37 [running]:
github.com/andersfylling/disgord.(*User).UnmarshalJSON(0x0, 0xc0001fc750, 0xc4, 0xd0, 0x0, 0x0)
        /Users/jake/go/pkg/mod/github.com/andersfylling/disgord@v0.17.3-0.20200531152814-ffadd6c09a34/user.go:477 +0xe3
github.com/json-iterator/go.(*unmarshalerDecoder).Decode(0xc0002cc0e0, 0xc000718070, 0xc000528000)
        /Users/jake/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_marshaler.go:199 +0xb3
github.com/json-iterator/go.(*referenceDecoder).Decode(0xc0002cc110, 0xc0000e6240, 0xc000528000)
        /Users/jake/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_optional.go:132 +0x68
github.com/json-iterator/go.(*Iterator).ReadVal(0xc000528000, 0x14c80e0, 0xc0000e6240)
        /Users/jake/go/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:79 +0xc1
github.com/json-iterator/go.(*frozenConfig).Unmarshal(0xc00011abe0, 0xc0001fc680, 0xc4, 0xd0, 0x14c80e0, 0xc0000e6240, 0x0, 0x0)
        /Users/jake/go/pkg/mod/github.com/json-iterator/go@v1.1.9/config.go:348 +0xb7
github.com/andersfylling/disgord/internal/util.Unmarshal(...)
        /Users/jake/go/pkg/mod/github.com/andersfylling/disgord@v0.17.3-0.20200531152814-ffadd6c09a34/internal/util/json_iter.go:22
github.com/andersfylling/disgord.populateResource(0x1584fc0, 0xc0000e6240, 0x1589d40, 0xc0000280c0, 0xc000034810, 0xc0001f0030, 0xc)
        /Users/jake/go/pkg/mod/github.com/andersfylling/disgord@v0.17.3-0.20200531152814-ffadd6c09a34/reactor.go:26 +0xc7
github.com/andersfylling/disgord.demultiplexer(0xc000076740, 0xc000078420, 0xc0001601e0)
        /Users/jake/go/pkg/mod/github.com/andersfylling/disgord@v0.17.3-0.20200531152814-ffadd6c09a34/reactor.go:65 +0x172
created by github.com/andersfylling/disgord.(*Client).setupConnectEnv
        /Users/jake/go/pkg/mod/github.com/andersfylling/disgord@v0.17.3-0.20200531152814-ffadd6c09a34/client.go:393 +0x20f
exit status 2
```

**Comment by andersfylling** [comment]
Whops indeed. I dug deeper. I found the issue, replicated it as a test and patched it.

Also added user flags, locale and public flags.

related #302
