### ISSUE TITLE
Panic after connection lost and attempted reconnect

### ISSUE THREAD

**Issue by DustinVFP** [andersfylling/disgord#98]
Panic when connection is lost and attempted reconnection

Output log
```INFO[0001] Connecting to discord Gateway                 lib="Disgord v0.9.0"
INFO[0001] Connected                                     lib="Disgord v0.9.0"
2018-12-11 09:53.50AM  > Info > debug check : 10
2018-12-11 09:53.50AM  | Info |  test
2018-12-11 09:53.50AM  > Info > Running under user : Natsubot#6309{516941386369597441}
INFO[18154] heartbeat ACK was not received, forcing reconnect 
INFO[18163] reconnect failed, trying again in N seconds; N =  3 
INFO[18163] dial tcp 104.16.59.37:443: connect: network is unreachable 
INFO[18166] successfully reconnected                     
INFO[20850] heartbeat ACK was not received, forcing reconnect 
INFO[20852] successfully reconnected                     
INFO[20862] Discord invalidated session                  
panic: runtime error: slice bounds out of range [recovered]
	panic: runtime error: slice bounds out of range

goroutine 537 [running]:
io/ioutil.readAll.func1(0x1044f30)
	/usr/local/go/src/io/ioutil/ioutil.go:30 +0xe0
panic(0x3562d8, 0x67bf18)
	/usr/local/go/src/runtime/panic.go:513 +0x194
bufio.(*Reader).Read(0x1256b40, 0x136ce00, 0x37, 0x1000, 0xcb600, 0x136c000, 0x13b4000)
	/usr/local/go/src/bufio/bufio.go:227 +0x3ac
github.com/gorilla/websocket.(*messageReader).Read(0x12b61f8, 0x136ce00, 0x1000, 0x1000, 0x800, 0x0, 0x0)
	/home/pi/MyCode/golang/.goPacks/src/github.com/gorilla/websocket/conn.go:988 +0x22c
bytes.(*Buffer).ReadFrom(0x10887e0, 0x6534e098, 0x12b61f8, 0x2a4714, 0x350b00, 0x357390, 0x101e500)
	/usr/local/go/src/bytes/buffer.go:206 +0xa8
io/ioutil.readAll(0x6534e098, 0x12b61f8, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/ioutil/ioutil.go:36 +0xa0
io/ioutil.ReadAll(0x6534e098, 0x12b61f8, 0x6534e098, 0x12b61f8, 0x0, 0x0, 0x1044fd0)
	/usr/local/go/src/io/ioutil/ioutil.go:45 +0x34
github.com/gorilla/websocket.(*Conn).ReadMessage(0x10f00c0, 0x0, 0x0, 0x1d2, 0x114a3c0, 0x1044f74, 0x123c080)
	/home/pi/MyCode/golang/.goPacks/src/github.com/gorilla/websocket/conn.go:1033 +0x6c
github.com/andersfylling/disgord/websocket.(*gorilla).Read(0x100ecf8, 0x101e4c0, 0x100, 0x600, 0x0, 0x0)
	/home/pi/MyCode/golang/.goPacks/src/github.com/andersfylling/disgord/websocket/websocket_gorilla.go:72 +0x28
github.com/andersfylling/disgord/websocket.(*Client).receiver(0x10ee0f0)
	/home/pi/MyCode/golang/.goPacks/src/github.com/andersfylling/disgord/websocket/client.go:311 +0x28
created by github.com/andersfylling/disgord/websocket.(*Client).Connect
	/home/pi/MyCode/golang/.goPacks/src/github.com/andersfylling/disgord/websocket/client.go:171 +0x134
```

expected behaviour: properly reconnects to discord when internet connection returns
what happened: crash/panic

session config:
```
session, err := disgord.NewSession(&disgord.Config{
	Token: conf_Token,
	Debug: true,
})
```

go version go1.11.2 linux/arm
operating system: linux/arm

**Comment by andersfylling** [comment]
A possible fix has been added. Please update your branch and let me know if it helped. I'm struggling to replicate this, to testing is difficult.
